run: Add workaround for Ubuntu version conflict in Docker
There is a known issue when the host operating system is Ubuntu 20.04 and
the container is running Ubuntu 22.04.

To mitigate this issue, the Docker container is run with the
`--security-opt seccomp=unconfined` option, which disables the default
seccomp profile. This allows the container to use the full set of
system calls available on the host, avoiding compatibility issues
caused by restricted or differently handled system calls.

The following function checks the host and container versions and sets
the `QUIRKS` variable accordingly. This variable is then used in the
`docker run` command to apply the necessary workaround.

Fixes the following error when building Yocto Mickledore 6.1.36 on a
Ubuntu 20.04 host using a Ubuntu 22.04 container:

| (glib-compile-resources:1288094): GLib-GIO-CRITICAL **: 18:58:57.343: g_subprocess_wait: assertion 'G_IS_SUBPROCESS (subprocess)' failed
|
| (glib-compile-resources:1288094): GLib-GObject-CRITICAL **: 18:58:57.344: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
| ../gdk-pixbuf-2.42.10/tests/resources.gresource.xml: Failed to close file descriptor for child process (Operation not permitted).
| [235/247] /workdir/build_xwayland/tmp/work/x86_64-linux/gdk-pixbuf-native/2.42.10-r0/recipe-sysroot-native/usr/bin/nativepython3 /workdir/build_xwayland/tmp/work/x86_64-linux/gdk-pixbuf-native/2.42.10-r0/gdk-pixbuf-2.42.10/build-aux/gen-thumbnailer.py --printer=/workdir/build_xwayland/tmp/work/x86_64-linux/gdk-pixbuf-native/2.42.10-r0/build/thumbnailer/gdk-pixbuf-print-mime-types --pixdata=/workdir/build_xwayland/tmp/work/x86_64-linux/gdk-pixbuf-native/2.42.10-r0/build/gdk-pixbuf/gdk-pixbuf-pixdata --loaders=/workdir/build_xwayland/tmp/work/x86_64-linux/gdk-pixbuf-native/2.42.10-r0/build/gdk-pixbuf/loaders.cache --bindir=/workdir/build_xwayland/tmp/work/x86_64-linux/gdk-pixbuf-native/2.42.10-r0/recipe-sysroot-native/usr/bin ../gdk-pixbuf-2.42.10/thumbnailer/gdk-pixbuf-thumbnailer.thumbnailer.in thumbnailer/gdk-pixbuf-thumbnailer.thumbnailer
| ninja: build stopped: subcommand failed.
| INFO: autodetecting backend as ninja
| INFO: calculating backend command to run: /workdir/build_xwayland/tmp/work/x86_64-linux/gdk-pixbuf-native/2.42.10-r0/recipe-sysroot-native/usr/bin/ninja -j 32 -v
| WARNING: /workdir/build_xwayland/tmp/work/x86_64-linux/gdk-pixbuf-native/2.42.10-r0/temp/run.do_compile.1283694:158 exit 1 from 'meson compile -v -j 32'
| WARNING: Backtrace (BB generated script):
|       #1: meson_do_compile, /workdir/build_xwayland/tmp/work/x86_64-linux/gdk-pixbuf-native/2.42.10-r0/temp/run.do_compile.1283694, line 158
|       #2: do_compile, /workdir/build_xwayland/tmp/work/x86_64-linux/gdk-pixbuf-native/2.42.10-r0/temp/run.do_compile.1283694, line 153
|       #3: main, /workdir/build_xwayland/tmp/work/x86_64-linux/gdk-pixbuf-native/2.42.10-r0/temp/run.do_compile.1283694, line 162
ERROR: Task (virtual:native:/workdir/sources/poky/meta/recipes-gnome/gdk-pixbuf/gdk-pixbuf_2.42.10.bb:do_compile) failed with exit code '1'

References:
- https://e2e.ti.com/support/processors-group/processors/f/processors-forum/1321924/j721excpxevm-yocto-build-always-gives-an-error-for-gdk-pixbuf_2-42-10-bb-do_compile

Signed-off-by: Nate Drude <nate.d@variscite.com>